### ISSUE TITLE
Feature Request Review

### ISSUE THREAD

**Issue by mp1pro** [johnwonderbread/bwa-u4-feature-request#2]
Allowing the user to add a track based on its popularity will improve the efficiency and usability of the app. Adding the `track.popularity` in the existing API call is the right approach. Great job using `this.props.track.popularity` to render the popularity value. Your caveat can be resolved with some clever html/css design updates. The feature was well detailed and plausible. Great feature request.

**Comment by johnwonderbread** [comment]
Thanks, @mp1pro!
